### ISSUE TITLE
Testing 

### ISSUE THREAD

**Issue by Aptronymist** [Nekos4Lyfe/TokenMixer#1]
Hi, we exchanged a few messages on reddit, I'm still quite eager to test your extension, if you have made enough progress on it. Might be able to provide you with a contributor too. Hit me up on discord, Aptronym.

**Comment by Nekos4Lyfe** [comment]
Hello! 
Yes, first version of the TokenMixer is available now. Feel free to try it out. It has a lot of new features and you will find it to be quite the improvement from the Embedding Inspector code.

Goal right now is to present all this new stuff on this github page with some images. Then solve an issue with "Interpolate Mode"  ( This mode merges vectors together that have a certain similarity ,  so it is not exactly interpolation but this is the placeholder name for now. ) where I cannot retain the input tokens after processing them. 

And then I plan on adding a Seecoder module to the TokenMixer, allowing the user to create latent vector from input images.

Then I think I will move on to do some actual interpolation of the vectors. Primary candidate here will be SLERP interpolation. This will yield a continues list of values. A cool thing would be to sample these values as a gif. 

That's the plan for now. Feel free to use this code for your own projects if you wish. 
And thanks for the support :)!
