### ISSUE TITLE
Errors with SD.Next

### ISSUE THREAD

**Issue by Aptronymist** [Nekos4Lyfe/TokenMixer#2]
I think this is just due to to the backend/SDXL based on the error message, so it's not necessarily an issue per se, but I thought I should inform you.
Since SD.Next can switch between backends at will, and of course load up SDXL models, if you start in SDXL mode, TokenMixer flips out with the following (completely understandable) error, which prevents it from loading at all. If started in original mode it's fine.

```
21:32:57-537639 ERROR    Module load: H:\AI\SD.Next\extensions\TokenMixer\scripts\main.py: AttributeError
┌─────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────┐
│ H:\AI\SD.Next\modules\script_loading.py:13 in load_module                                        
│                                                                                                                                        
│   12 │   try:                                                                                                                          
│ > 13 │   │   module_spec.loader.exec_module(module)                                                 
│   14 │   except Exception as e:                                                                                        
│ in exec_module:883                                                                                                        
│                                                                                                                                      
│                                                         ... 6 frames hidden ...                                                       
│                                                                                                                                     
│ H:\AI\SD.Next\extensions\TokenMixer\lib\toolbox\tools.py:31 in get                                                        
│                                                                                                                                     
│   30 │   │   │   key=lambda x: str(x[0]).lower()))                                                                                
│ > 31 │   │   embedder = shared.sd_model.cond_stage_model.wrapped                                                               
│   32 │   │   if embedder.__class__.__name__=='FrozenCLIPEmbedder': # SD1.x detected                                    
│                                                                                                                                       
│ H:\AI\SD.Next\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__                                 
│                                                                                                                                      
│   136 │   │                                                                                                                            
│ > 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                            
│   138                                                                                                                                  
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'cond_stage_model'
```

This does make me wonder if you have plans for SDXL though!

**Comment by Nekos4Lyfe** [comment]
I can try! I haven't made any tests with the SDXL model at all yet. 
But the dependency is very light.

I will need to figure out how to fetch :

a) The tokenizer for SDXL and
b) the internal CLIP embeddings for SDXL

Then the TokenMixer should be good to go with SDXL.
I will see what I can do...

**Comment by Nekos4Lyfe** [comment]
I have made a new upload. See if this works:
![Check](https://github.com/Nekos4Lyfe/TokenMixer/assets/130230016/244c3fb0-fa3b-4e86-a81c-c0bb8eb44225)


Unfortunately, I don't have the VRAM to run SDXL on my device.  

Also: I have added a new module to the TokenMixer called the Cross Attention Visualizer: https://github.com/bloc97/CrossAttentionControl/blob/main/CrossAttention_Release.ipynb

This module might cause problems for SDXL as well. If it does, let me know.

Hopefully there will be a low-VRAM version of SDXL  released sometime in the future that I can use for testing. 

In the meantime I recommend forking the TokenMixer over to someone else who can implement compatibility with SDXL

**Comment by Aptronymist** [comment]
> 

When vlad has a chance, rest assured he'll probably help you out with adjusting to using SDXL with this extension, in regards to it actually being able to work  with tokenizer and internal CLIP that is. When he's settled in I'll let him know, that would be a first as far as SDXL as far as I know.
