### ISSUE TITLE
Extension incompatibiilty: DepthMap script

### ISSUE THREAD

**Issue by semjonsona** [Nekos4Lyfe/TokenMixer#7]
Hello

There is a report from a person who encountered an incompatibility. Please see here: https://github.com/thygate/stable-diffusion-webui-depthmap-script/issues/336

**Comment by Nekos4Lyfe** [comment]
You can mark that one as "Completed".  Issue was that the TokenMixer/lib folder was shadowing the Depthmap/lib folder.

 I changed the name of the "lib" folder in TokenMixer to "library" to solve this.

**Comment by semjonsona** [comment]
Thanks!
